### PR TITLE
Update Footer.tsx

### PR DESCRIPTION
**Pull request by Bashamega**
fix: #2 
I have added the react icons, please accept it

### CODE REVIEW

**Comment by Ayushpanditmoto** [comment]
Screenshot_3


Do not touch the green part please this looks fine 

only touch icon part

**Comment by Ayushpanditmoto** [comment]
Screenshot_4
This is not good

**Comment by Bashamega** [comment]
Thanks. I will work on it today

**Comment by Bashamega** [comment]
do you like these
image
or prefer this
image
They also have a cool hovering effect

**Comment by Bashamega** [comment]
> do you like these image or prefer this image They also have a cool hovering effect

@Ayushpanditmoto

**Pull request closed without merging**
