### PR TITLE
Updated About Us page

### PR DESCRIPTION
**Pull request by Cshiva773**
Screenshot (16)
Screenshot (17)

In this improved version:

I've organized the content into sections with appropriate headings for better readability and structure.
I've added more styling to make the content visually appealing, including spacing and blockquote for the testimonial.
I've used a grid layout for the "Services" section to display multiple services side by side on larger screens.
I've updated the formatting for the list of portfolio projects for better clarity.
I've included a blue border to make the testimonial stand out.

### CODE REVIEW

**Comment by Ayushpanditmoto** [comment]
@Cshiva773  can you create this one on markdown file

**Comment by Cshiva773** [comment]
Sure i will try

**Comment by Ayushpanditmoto** [comment]
@Cshiva773  use Image by next js instead of img

**Comment by Cshiva773** [comment]
I have updated the codebase as per your feedback

**Review by marki2121 — APPROVED** [review]

**Pull request closed without merging**
